name: Build and Deploy to GKE

on:
  workflow_dispatch:

env:
  PROJECT_ID: ${{secrets.GKE_PROJECT}}
  GKE_CLUSTER: genhub
  GKE_ZONE: europe-north1-a
  DEPLOYMENT_NAME: Genhub-test
  IMAGE: codbex-genetyllis-platform-runtime:latest
  

jobs:
  build:
#     name: Setup Build Publsh Deploy

    runs-on: ubuntu-latest

    steps:

      # - name: Chekout Repo
      #   uses: actions/checkout@v2

      # - name: Setup JDK 1.8
      #   uses: actions/setup-java@v1
      #   with:
      #     java-version: 1.8
      #     server-id: github
      #     settings-path: ${{github.workspace}}

      # - name: Build with Maven
      #   run: nvm clean package -DskipTests

      - name: Setup Google Cloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          service_account_key: ${{secrets.GKE_SA_KEY}}
          project_id: ${{secrets.GKE_PROJECT}}



      - name: Get GKE Credentials
        run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE" --project "$PROJECT_ID"
        
      - name: Check cluster
        run: kubectl get pods -n dirigible-demo

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest' # default is latest (stable)
        id: install 

      - name: Add Dirigible-Helm Repo
        run: |-
          helm repo add dirigible https://eclipse.github.io/dirigible 
          helm repo update

      - name: Deploy Genhub App
        run: |-
          helm upgrade --install app dirigible/dirigible -n dirigible-demo \
          --set volume.enabled=true \
          --set serviceAccount.create=false \
          --set keycloak.serviceAccountCreate=false \
          --set ingress.tls=true \
          --set keycloak.enabled=true \
          --set keycloak.install=true \
          --set istio.enabled=true \
          --set istio.enableHttps=true \
          --set gke.cloudSQL=true \
          --set gke.projectId=genetic-platform \
          --set gke.region=europe-north1 \
          --set ingress.host=gen.apps.quanterall.com \
          --set gke.dirigibleSqlInstanceName=genhub \
          --set gke.keycloakSqlInstanceName=keycloak \
          --set dirigible.image=ghcr.io/codbex/codbex-genetyllis-keycloack-runtime:latest
